server {
    listen 80;

    location /api/ {
        proxy_pass http://apicreapes.leanttro.com/api/;
        proxy_set_header Host apicreapes.leanttro.com;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
